server:
  port: 8083
  address: localhost

spring:
  ldap:
    embedded:
      base-dn: dc=embedded,dc=ldap
      ldif: classpath:config.ldif
      port: 8084
      credential:
        username: uid=admin
        password: secret
      validation:
        enabled: false